### ISSUE TITLE
Dependency could not be satisfied

### ISSUE THREAD

**Issue by mikecsh** [qutheory/vapor-mustache#18]
Currently not compatible with the latest version of Vapor.

**Comment by tanner0101** [comment]
We haven't updated this since having released [Leaf](https://github.com/vapor/leaf) templates.

**Comment by mikecsh** [comment]
Hi @tannernelson, thanks for your response - can I take it from this that vapor/mustache-provider is deprecated and will not be updated?

**Comment by tanner0101** [comment]
I don't have any plans to update it, but someone from the community might. Your best bet would be using Leaf, though. It's included with Vapor!

**Comment by mikecsh** [comment]
Thanks. Unfortunately Leaf is not an option as the project has a hard dependency on Mustache for now. If I can find time I'll make an adaptor for GRMustache.swift which is what we use client side.

**Comment by tanner0101** [comment]
I believe Perfect and Kitura have mustache parsers that you could use with Vapor.
