### ISSUE TITLE
Does not add using "vapor xcode"

### ISSUE THREAD

**Issue by steve-h** [qutheory/vapor-mustache#21]
tried: .Package(url: "https://github.com/vapor/mustache-provider.git", majorVersion: 0, minor: 10)

the documentation seems out of date after move to the Vapor account.

The package.swift file refers to a Vapor version: 0.14.0 that does not exist - perhaps 1.4 is what would be better.

**Comment by tanner0101** [comment]
Mustache is no longer supported since we have https://github.com/vapor/leaf.
