### ISSUE TITLE
Dependency could not be satisfied

### ISSUE THREAD

**Issue by nmfzone** [qutheory/vapor-mustache#5]
Why when i try to use this Package in Vapor, it says that the dependency could not be satisfied?

Below is a piece of the error messages that come up,

```
Cloning https://github.com/Zewo/StructuredData.git
Resolved version: 0.7.1
Cloning https://github.com/qutheory/vapor-zewo-mustache.git
Resolved version: 0.1.1
Cloning https://github.com/Zewo/Mustache.git
Resolved version: 0.4.0
error: The dependency graph could not be satisfied (https://github.com/qutheory/vapor.git)

Make sure you are running Apple Swift version 3.0.
Vapor only supports the latest snapshot.
Run swift --version to check your version.

Error: Could not build project.
```

And below is my swift version,

```
Swift version 3.0-dev (LLVM dffa09ffd8, Clang 1e6cba3ce3, Swift d2aee43220)
Target: x86_64-unknown-linux-gnu
```

How do I fix this?

**Comment by nmfzone** [comment]
@LoganWright

**Comment by tanner0101** [comment]
Mustache is not currently supported in the `05-03` snapshot ( compiler bugs D: ). It will work again in the next snapshot which should come in a week or so.

**Comment by loganwright** [comment]
@nmfzone in the meantime, there's some examples working around it a bit on 05-03 snapshot!

\- https://github.com/mjmsmith/starredsearch
- https://github.com/rosslebeau/bytefish
